language: python
env: FLASK_ENV=test
install: 
  - pip install -r requirements.txt --use-mirrors
  - cp config.yaml.example config.yaml
  - createuser -P -s denverstreetsuser
  - ./bin/setup_db
script: ./run_tests

